anchor_version = "0.18.2"

[workspace]
members = ["programs/eywa-bridge", "programs/eywa-gas-tank", "programs/eywa-portal-synthesis", "programs/test-token-faucet", "programs/test-stub"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:internal"
