// source: eywa_solana.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.eywa_solana_grpc.OracleRequest', null, global);
goog.exportSymbol('proto.eywa_solana_grpc.SlotInfo', null, global);
goog.exportSymbol('proto.eywa_solana_grpc.uinteger160', null, global);
goog.exportSymbol('proto.eywa_solana_grpc.uinteger256', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.eywa_solana_grpc.uinteger256 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.eywa_solana_grpc.uinteger256, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.eywa_solana_grpc.uinteger256.displayName = 'proto.eywa_solana_grpc.uinteger256';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.eywa_solana_grpc.uinteger160 = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.eywa_solana_grpc.uinteger160, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.eywa_solana_grpc.uinteger160.displayName = 'proto.eywa_solana_grpc.uinteger160';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.eywa_solana_grpc.OracleRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.eywa_solana_grpc.OracleRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.eywa_solana_grpc.OracleRequest.displayName = 'proto.eywa_solana_grpc.OracleRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.eywa_solana_grpc.SlotInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.eywa_solana_grpc.SlotInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.eywa_solana_grpc.SlotInfo.displayName = 'proto.eywa_solana_grpc.SlotInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.eywa_solana_grpc.uinteger256.prototype.toObject = function(opt_includeInstance) {
  return proto.eywa_solana_grpc.uinteger256.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.eywa_solana_grpc.uinteger256} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.uinteger256.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: msg.getValue_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.eywa_solana_grpc.uinteger256}
 */
proto.eywa_solana_grpc.uinteger256.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.eywa_solana_grpc.uinteger256;
  return proto.eywa_solana_grpc.uinteger256.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.eywa_solana_grpc.uinteger256} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.eywa_solana_grpc.uinteger256}
 */
proto.eywa_solana_grpc.uinteger256.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.uinteger256.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.eywa_solana_grpc.uinteger256.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.eywa_solana_grpc.uinteger256} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.uinteger256.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes value = 1;
 * @return {!(string|Uint8Array)}
 */
proto.eywa_solana_grpc.uinteger256.prototype.getValue = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes value = 1;
 * This is a type-conversion wrapper around `getValue()`
 * @return {string}
 */
proto.eywa_solana_grpc.uinteger256.prototype.getValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getValue()));
};


/**
 * optional bytes value = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getValue()`
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.uinteger256.prototype.getValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getValue()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.eywa_solana_grpc.uinteger256} returns this
 */
proto.eywa_solana_grpc.uinteger256.prototype.setValue = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.eywa_solana_grpc.uinteger160.prototype.toObject = function(opt_includeInstance) {
  return proto.eywa_solana_grpc.uinteger160.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.eywa_solana_grpc.uinteger160} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.uinteger160.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: msg.getValue_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.eywa_solana_grpc.uinteger160}
 */
proto.eywa_solana_grpc.uinteger160.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.eywa_solana_grpc.uinteger160;
  return proto.eywa_solana_grpc.uinteger160.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.eywa_solana_grpc.uinteger160} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.eywa_solana_grpc.uinteger160}
 */
proto.eywa_solana_grpc.uinteger160.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.uinteger160.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.eywa_solana_grpc.uinteger160.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.eywa_solana_grpc.uinteger160} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.uinteger160.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes value = 1;
 * @return {!(string|Uint8Array)}
 */
proto.eywa_solana_grpc.uinteger160.prototype.getValue = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes value = 1;
 * This is a type-conversion wrapper around `getValue()`
 * @return {string}
 */
proto.eywa_solana_grpc.uinteger160.prototype.getValue_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getValue()));
};


/**
 * optional bytes value = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getValue()`
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.uinteger160.prototype.getValue_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getValue()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.eywa_solana_grpc.uinteger160} returns this
 */
proto.eywa_solana_grpc.uinteger160.prototype.setValue = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.eywa_solana_grpc.OracleRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.eywa_solana_grpc.OracleRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.OracleRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestType: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bridge: (f = msg.getBridge()) && proto.eywa_solana_grpc.uinteger256.toObject(includeInstance, f),
    requestId: (f = msg.getRequestId()) && proto.eywa_solana_grpc.uinteger256.toObject(includeInstance, f),
    selector: msg.getSelector_asB64(),
    receiveSide: (f = msg.getReceiveSide()) && proto.eywa_solana_grpc.uinteger160.toObject(includeInstance, f),
    oppositeBridge: (f = msg.getOppositeBridge()) && proto.eywa_solana_grpc.uinteger160.toObject(includeInstance, f),
    chainid: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.eywa_solana_grpc.OracleRequest}
 */
proto.eywa_solana_grpc.OracleRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.eywa_solana_grpc.OracleRequest;
  return proto.eywa_solana_grpc.OracleRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.eywa_solana_grpc.OracleRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.eywa_solana_grpc.OracleRequest}
 */
proto.eywa_solana_grpc.OracleRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestType(value);
      break;
    case 2:
      var value = new proto.eywa_solana_grpc.uinteger256;
      reader.readMessage(value,proto.eywa_solana_grpc.uinteger256.deserializeBinaryFromReader);
      msg.setBridge(value);
      break;
    case 3:
      var value = new proto.eywa_solana_grpc.uinteger256;
      reader.readMessage(value,proto.eywa_solana_grpc.uinteger256.deserializeBinaryFromReader);
      msg.setRequestId(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSelector(value);
      break;
    case 5:
      var value = new proto.eywa_solana_grpc.uinteger160;
      reader.readMessage(value,proto.eywa_solana_grpc.uinteger160.deserializeBinaryFromReader);
      msg.setReceiveSide(value);
      break;
    case 6:
      var value = new proto.eywa_solana_grpc.uinteger160;
      reader.readMessage(value,proto.eywa_solana_grpc.uinteger160.deserializeBinaryFromReader);
      msg.setOppositeBridge(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setChainid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.eywa_solana_grpc.OracleRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.eywa_solana_grpc.OracleRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.OracleRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBridge();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.eywa_solana_grpc.uinteger256.serializeBinaryToWriter
    );
  }
  f = message.getRequestId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.eywa_solana_grpc.uinteger256.serializeBinaryToWriter
    );
  }
  f = message.getSelector_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getReceiveSide();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.eywa_solana_grpc.uinteger160.serializeBinaryToWriter
    );
  }
  f = message.getOppositeBridge();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.eywa_solana_grpc.uinteger160.serializeBinaryToWriter
    );
  }
  f = message.getChainid();
  if (f !== 0) {
    writer.writeFixed64(
      7,
      f
    );
  }
};


/**
 * optional string request_type = 1;
 * @return {string}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getRequestType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.setRequestType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uinteger256 bridge = 2;
 * @return {?proto.eywa_solana_grpc.uinteger256}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getBridge = function() {
  return /** @type{?proto.eywa_solana_grpc.uinteger256} */ (
    jspb.Message.getWrapperField(this, proto.eywa_solana_grpc.uinteger256, 2));
};


/**
 * @param {?proto.eywa_solana_grpc.uinteger256|undefined} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
*/
proto.eywa_solana_grpc.OracleRequest.prototype.setBridge = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.clearBridge = function() {
  return this.setBridge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.hasBridge = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uinteger256 request_id = 3;
 * @return {?proto.eywa_solana_grpc.uinteger256}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getRequestId = function() {
  return /** @type{?proto.eywa_solana_grpc.uinteger256} */ (
    jspb.Message.getWrapperField(this, proto.eywa_solana_grpc.uinteger256, 3));
};


/**
 * @param {?proto.eywa_solana_grpc.uinteger256|undefined} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
*/
proto.eywa_solana_grpc.OracleRequest.prototype.setRequestId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.clearRequestId = function() {
  return this.setRequestId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.hasRequestId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional bytes selector = 4;
 * @return {!(string|Uint8Array)}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getSelector = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes selector = 4;
 * This is a type-conversion wrapper around `getSelector()`
 * @return {string}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getSelector_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSelector()));
};


/**
 * optional bytes selector = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSelector()`
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getSelector_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSelector()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.setSelector = function(value) {
  return jspb.Message.setProto3BytesField(this, 4, value);
};


/**
 * optional uinteger160 receive_side = 5;
 * @return {?proto.eywa_solana_grpc.uinteger160}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getReceiveSide = function() {
  return /** @type{?proto.eywa_solana_grpc.uinteger160} */ (
    jspb.Message.getWrapperField(this, proto.eywa_solana_grpc.uinteger160, 5));
};


/**
 * @param {?proto.eywa_solana_grpc.uinteger160|undefined} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
*/
proto.eywa_solana_grpc.OracleRequest.prototype.setReceiveSide = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.clearReceiveSide = function() {
  return this.setReceiveSide(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.hasReceiveSide = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional uinteger160 opposite_bridge = 6;
 * @return {?proto.eywa_solana_grpc.uinteger160}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getOppositeBridge = function() {
  return /** @type{?proto.eywa_solana_grpc.uinteger160} */ (
    jspb.Message.getWrapperField(this, proto.eywa_solana_grpc.uinteger160, 6));
};


/**
 * @param {?proto.eywa_solana_grpc.uinteger160|undefined} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
*/
proto.eywa_solana_grpc.OracleRequest.prototype.setOppositeBridge = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.clearOppositeBridge = function() {
  return this.setOppositeBridge(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.hasOppositeBridge = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional fixed64 chainid = 7;
 * @return {number}
 */
proto.eywa_solana_grpc.OracleRequest.prototype.getChainid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.eywa_solana_grpc.OracleRequest} returns this
 */
proto.eywa_solana_grpc.OracleRequest.prototype.setChainid = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.eywa_solana_grpc.SlotInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.eywa_solana_grpc.SlotInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.eywa_solana_grpc.SlotInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.SlotInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    slot: jspb.Message.getFieldWithDefault(msg, 1, 0),
    parent: jspb.Message.getFieldWithDefault(msg, 2, 0),
    root: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.eywa_solana_grpc.SlotInfo}
 */
proto.eywa_solana_grpc.SlotInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.eywa_solana_grpc.SlotInfo;
  return proto.eywa_solana_grpc.SlotInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.eywa_solana_grpc.SlotInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.eywa_solana_grpc.SlotInfo}
 */
proto.eywa_solana_grpc.SlotInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setSlot(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setParent(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFixed64());
      msg.setRoot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.eywa_solana_grpc.SlotInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.eywa_solana_grpc.SlotInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.eywa_solana_grpc.SlotInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.eywa_solana_grpc.SlotInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSlot();
  if (f !== 0) {
    writer.writeFixed64(
      1,
      f
    );
  }
  f = message.getParent();
  if (f !== 0) {
    writer.writeFixed64(
      2,
      f
    );
  }
  f = message.getRoot();
  if (f !== 0) {
    writer.writeFixed64(
      3,
      f
    );
  }
};


/**
 * optional fixed64 slot = 1;
 * @return {number}
 */
proto.eywa_solana_grpc.SlotInfo.prototype.getSlot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.eywa_solana_grpc.SlotInfo} returns this
 */
proto.eywa_solana_grpc.SlotInfo.prototype.setSlot = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional fixed64 parent = 2;
 * @return {number}
 */
proto.eywa_solana_grpc.SlotInfo.prototype.getParent = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.eywa_solana_grpc.SlotInfo} returns this
 */
proto.eywa_solana_grpc.SlotInfo.prototype.setParent = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional fixed64 root = 3;
 * @return {number}
 */
proto.eywa_solana_grpc.SlotInfo.prototype.getRoot = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.eywa_solana_grpc.SlotInfo} returns this
 */
proto.eywa_solana_grpc.SlotInfo.prototype.setRoot = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.eywa_solana_grpc);
